export type Contract = {
  id: string;
  name: string;
  vendor: string;
  cnpj: string;
  destination: string;
  start: string;
  end: string;
  endDate: string;
  automatic: boolean;
  renewalPeriodMonths?: number | null;
  notice: number;
  noticeUnit?: 'calendar_days' | 'business_days' | 'months';
  penalty: boolean;
  penaltyBase: string;
  billing: string;
  value: number;
  adjustment: string;
  costCenter: string;
  squad: string;
  manager: string;
  sla: string;
  systems: string;
  criticality: 'Alta' | 'Média' | 'Baixa';
  status: 'Vigente' | 'Em renovação' | 'Encerrado' | 'Cancelado';
  lgpd: string;
};

export const TODAY = new Date(2026, 8, 1);

export const contracts: Contract[] = [
  {
    id: 'CTR-2026-0142',
    name: 'Plataforma de frete inteligente',
    vendor: 'Fretex Tecnologia',
    cnpj: '12.345.678/0001-90',
    destination: '1P e 3P',
    start: '01/11/2024',
    end: '31/10/2026',
    endDate: '2026-10-31',
    automatic: true,
    notice: 60,
    penalty: true,
    penaltyBase: '30% do valor remanescente',
    billing: 'Mensal',
    value: 18400,
    adjustment: 'IPCA',
    costCenter: 'CC-1042',
    squad: 'Logística',
    manager: 'Rafael Coutinho',
    sla: '99,5% de disponibilidade',
    systems: 'OMS, Hub de marketplaces',
    criticality: 'Alta',
    status: 'Vigente',
    lgpd: 'Cláusula de confidencialidade + DPA assinado',
  },
  {
    id: 'CTR-2025-0088',
    name: 'Hub de integração de marketplaces',
    vendor: 'Anymarket',
    cnpj: '09.876.543/0001-21',
    destination: '3P',
    start: '15/09/2024',
    end: '14/09/2026',
    endDate: '2026-09-14',
    automatic: true,
    notice: 30,
    penalty: true,
    penaltyBase: '2 mensalidades',
    billing: 'Mensal',
    value: 32750,
    adjustment: 'IGP-M',
    costCenter: 'CC-2201',
    squad: 'Marketplace',
    manager: 'Juliana Prado',
    sla: '99,9% de disponibilidade',
    systems: 'ERP, OMS',
    criticality: 'Alta',
    status: 'Em renovação',
    lgpd: 'DPA assinado',
  },
  {
    id: 'CTR-2024-0311',
    name: 'Licenças de ERP — módulo fiscal',
    vendor: 'Sankhya',
    cnpj: '11.222.333/0001-44',
    destination: 'TI',
    start: '01/01/2025',
    end: '31/12/2026',
    endDate: '2026-12-31',
    automatic: false,
    notice: 90,
    penalty: false,
    penaltyBase: '—',
    billing: 'Anual',
    value: 214000,
    adjustment: 'IPCA',
    costCenter: 'CC-3010',
    squad: 'Plataforma',
    manager: 'Marcos Vieira',
    sla: 'Suporte 8x5, resposta em 4h',
    systems: 'ERP',
    criticality: 'Alta',
    status: 'Vigente',
    lgpd: 'Confidencialidade padrão',
  },
  {
    id: 'CTR-2026-0155',
    name: 'Gateway de pagamentos',
    vendor: 'Pagar.me',
    cnpj: '22.333.444/0001-55',
    destination: '1P',
    start: '01/03/2026',
    end: '28/02/2027',
    endDate: '2027-02-28',
    automatic: true,
    notice: 45,
    penalty: false,
    penaltyBase: '—',
    billing: 'Por uso / variável',
    value: 0,
    adjustment: 'Sem reajuste',
    costCenter: 'CC-1180',
    squad: 'Checkout',
    manager: 'Ana Beatriz Lima',
    sla: '99,95% de disponibilidade',
    systems: 'Checkout, ERP',
    criticality: 'Alta',
    status: 'Vigente',
    lgpd: 'PCI-DSS + DPA',
  },
  {
    id: 'CTR-2025-0203',
    name: 'Ferramenta de atendimento omnichannel',
    vendor: 'Zenvia',
    cnpj: '33.444.555/0001-66',
    destination: '1P e 3P',
    start: '01/10/2025',
    end: '30/09/2026',
    endDate: '2026-09-30',
    automatic: true,
    notice: 60,
    penalty: true,
    penaltyBase: '50% do saldo',
    billing: 'Mensal',
    value: 9800,
    adjustment: 'IPCA',
    costCenter: 'CC-1502',
    squad: 'Atendimento',
    manager: 'Camila Ferraz',
    sla: '99% de disponibilidade',
    systems: 'CRM',
    criticality: 'Média',
    status: 'Vigente',
    lgpd: 'DPA assinado',
  },
  {
    id: 'CTR-2024-0270',
    name: 'Antifraude e análise de risco',
    vendor: 'ClearSale',
    cnpj: '44.555.666/0001-77',
    destination: '1P',
    start: '01/06/2024',
    end: '31/05/2027',
    endDate: '2027-05-31',
    automatic: false,
    notice: 90,
    penalty: true,
    penaltyBase: '20% do valor remanescente',
    billing: 'Mensal',
    value: 27300,
    adjustment: 'IPCA',
    costCenter: 'CC-1180',
    squad: 'Checkout',
    manager: 'Ana Beatriz Lima',
    sla: 'Análise em até 24h',
    systems: 'Checkout, OMS',
    criticality: 'Alta',
    status: 'Vigente',
    lgpd: 'DPA + tratamento de dados sensíveis',
  },
  {
    id: 'CTR-2025-0119',
    name: 'Observabilidade e monitoramento',
    vendor: 'Datadog',
    cnpj: '55.666.777/0001-88',
    destination: 'TI',
    start: '01/08/2025',
    end: '31/07/2026',
    endDate: '2026-07-31',
    automatic: true,
    notice: 30,
    penalty: false,
    penaltyBase: '—',
    billing: 'Anual',
    value: 96000,
    adjustment: 'Sem reajuste',
    costCenter: 'CC-3010',
    squad: 'Plataforma',
    manager: 'Marcos Vieira',
    sla: 'Suporte 24x7',
    systems: 'Infra',
    criticality: 'Média',
    status: 'Encerrado',
    lgpd: 'Confidencialidade padrão',
  },
  {
    id: 'CTR-2026-0160',
    name: 'Consultoria de precificação dinâmica',
    vendor: 'Precifica',
    cnpj: '66.777.888/0001-99',
    destination: '3P',
    start: '01/04/2026',
    end: '31/03/2027',
    endDate: '2027-03-31',
    automatic: false,
    notice: 30,
    penalty: false,
    penaltyBase: '—',
    billing: 'Trimestral',
    value: 41000,
    adjustment: 'IPCA',
    costCenter: 'CC-2201',
    squad: 'Marketplace',
    manager: 'Juliana Prado',
    sla: 'Relatórios semanais',
    systems: 'Hub de marketplaces',
    criticality: 'Baixa',
    status: 'Vigente',
    lgpd: 'Confidencialidade padrão',
  },
  {
    id: 'CTR-2023-0044',
    name: 'Transportadora regional Sul',
    vendor: 'LogSul Transportes',
    cnpj: '77.888.999/0001-11',
    destination: 'Logística',
    start: '01/02/2024',
    end: '31/01/2027',
    endDate: '2027-01-31',
    automatic: true,
    notice: 120,
    penalty: true,
    penaltyBase: '3 faturas médias',
    billing: 'Mensal',
    value: 63500,
    adjustment: 'IGP-M',
    costCenter: 'CC-1042',
    squad: 'Logística',
    manager: 'Rafael Coutinho',
    sla: 'Coleta em D+1',
    systems: 'OMS, WMS',
    criticality: 'Alta',
    status: 'Vigente',
    lgpd: 'Confidencialidade padrão',
  },
  {
    id: 'CTR-2025-0177',
    name: 'Backoffice jurídico — assinatura eletrônica',
    vendor: 'Clicksign',
    cnpj: '88.999.000/0001-22',
    destination: 'Jurídico',
    start: '01/12/2025',
    end: '30/11/2026',
    endDate: '2026-11-30',
    automatic: true,
    notice: 30,
    penalty: false,
    penaltyBase: '—',
    billing: 'Anual',
    value: 14200,
    adjustment: 'IPCA',
    costCenter: 'CC-4001',
    squad: 'Corporativo',
    manager: 'Patrícia Nunes',
    sla: '99% de disponibilidade',
    systems: '—',
    criticality: 'Baixa',
    status: 'Vigente',
    lgpd: 'DPA assinado',
  },
];

export const notifications = [
  {
    id: 'n1',
    code: 'D0',
    title: 'Aviso prévio vence hoje — Plataforma de frete inteligente',
    text: 'Renovação automática ativa. Registre a decisão até o fim do dia para evitar renovação tácita por 12 meses.',
    tag: 'Crítico',
    when: '01/09/2026 08:00',
    channels: 'Tela + e-mail',
    contract: 'CTR-2026-0142',
    tone: 'danger',
  },
  {
    id: 'n2',
    code: '!',
    title: 'Prazo de aviso expirado — Hub de integração de marketplaces',
    text: 'O aviso prévio de 30 dias venceu em 15/08/2026. Renovação automática em 14/09/2026.',
    tag: 'Atrasado',
    when: '31/08/2026 08:00',
    channels: 'Tela + e-mail',
    contract: 'CTR-2025-0088',
    tone: 'danger',
  },
  {
    id: 'n3',
    code: '30',
    title: 'D-30 do fim da vigência — Ferramenta omnichannel',
    text: 'Vigência termina em 30/09/2026. Contrato com multa de 50% do saldo.',
    tag: 'Vigência',
    when: '31/08/2026 08:00',
    channels: 'Tela + e-mail',
    contract: 'CTR-2025-0203',
    tone: 'warning',
  },
  {
    id: 'n4',
    code: '%',
    title: 'Reajuste anual programado — Backoffice jurídico',
    text: 'IPCA acumulado de 4,1% será aplicado em 01/12/2026.',
    tag: 'Reajuste',
    when: '28/08/2026 08:00',
    channels: 'Tela',
    contract: 'CTR-2025-0177',
    tone: 'info',
  },
  {
    id: 'n5',
    code: '90',
    title: 'D-90 do fim da vigência — Licenças de ERP',
    text: 'Sem renovação automática. Novo aditivo precisa ser negociado até 02/10/2026.',
    tag: 'Vigência',
    when: '02/08/2026 08:00',
    channels: 'Tela + e-mail',
    contract: 'CTR-2024-0311',
    tone: 'warning',
  },
  {
    id: 'n6',
    code: 'DOC',
    title: 'Documento obrigatório ausente — Consultoria de precificação',
    text: 'Contrato cadastrado há 6 dias sem PDF assinado anexado.',
    tag: 'Documento',
    when: '25/08/2026 08:00',
    channels: 'Tela',
    contract: 'CTR-2026-0160',
    tone: 'neutral',
  },
] as const;

export const users = [
  [
    'Rafael Coutinho',
    'rafael.coutinho@webcontinental.com.br',
    'RC',
    'Produto',
    '3',
    '01/09/2026 08:12',
    'Ativo',
  ],
  [
    'Juliana Prado',
    'juliana.prado@webcontinental.com.br',
    'JP',
    'Marketplace',
    '2',
    '31/08/2026 17:45',
    'Ativo',
  ],
  [
    'Patrícia Nunes',
    'patricia.nunes@webcontinental.com.br',
    'PN',
    'Jurídico',
    '1',
    '29/08/2026 11:03',
    'Ativo',
  ],
  [
    'Marcos Vieira',
    'marcos.vieira@webcontinental.com.br',
    'MV',
    'Plataforma',
    '2',
    '28/08/2026 09:30',
    'Ativo',
  ],
  [
    'Ana Beatriz Lima',
    'ana.lima@webcontinental.com.br',
    'AL',
    'Checkout',
    '2',
    '22/08/2026 15:18',
    'Ativo',
  ],
  [
    'Camila Ferraz',
    'camila.ferraz@webcontinental.com.br',
    'CF',
    'Atendimento',
    '1',
    '—',
    'Convite pendente',
  ],
] as const;

export const money = (value: number) =>
  value
    ? new Intl.NumberFormat('pt-BR', {
        style: 'currency',
        currency: 'BRL',
      }).format(value)
    : '—';
export const daysUntil = (date: string) =>
  Math.round(
    (new Date(`${date}T12:00:00`).getTime() - TODAY.getTime()) / 86400000,
  );
export const formatDate = (date: Date) => date.toLocaleDateString('pt-BR');
export const decisionDate = (contract: Contract) =>
  new Date(
    new Date(`${contract.endDate}T12:00:00`).getTime() -
      contract.notice * 86400000,
  );
